algo = input('Digite algo: ')
print('isalnum', algo.isalnum())
print('isalpha', algo.isalpha())
print('isdigit', algo.isdigit())
print('isidentifier', algo.isidentifier())
print('islower', algo.islower())
print('isnumeric', algo.isnumeric())
print('isprintable', algo.isprintable())
print('istitle', algo.istitle())
